In [1]:
import pandas as pd
df = pd.read_csv("/content/drive/MyDrive/DX PROJ./유튜브 크롤링/층간소음_youtube_clean.csv")
df

,title,date,author,contents,contents_clean
0,엘베 안 흉기에 40차례…층간 소음 가해? &quot;억울해&quot; / JTBC...,19분 전,@쿠루쿠루뚜르뜨루뜨,건설사가 어디임?,건설사가 어디임
1,엘베 안 흉기에 40차례…층간 소음 가해? &quot;억울해&quot; / JTBC...,29분 전,@김선우-v3v,미친놈 부모가 젤 잘못,미친놈 부모가 잘못
2,엘베 안 흉기에 40차례…층간 소음 가해? &quot;억울해&quot; / JTBC...,57분 전,@김나스-k9r,가족들 그엘베 타는거 진짜 고역이겠다.. 어떻게 사냐 진짜,가족들 그엘베 타는거 고역이겠다 어떻게 사냐
3,엘베 안 흉기에 40차례…층간 소음 가해? &quot;억울해&quot; / JTBC...,1시간 전,@심종수-y7p,저런인가은정신병원영원히가둬라,저런인가은정신병원영원히가둬라
4,엘베 안 흉기에 40차례…층간 소음 가해? &quot;억울해&quot; / JTBC...,1시간 전,@은채이-b9u,대체 어느아파트?,어느아파트
...,...,...,...,...,...
45507,&quot;저도 층간소음 피해자입니다&quot; 소음전문 변호사가 소송 말리는 이유,3년 전,@worldclass2510Trillion,짐승들이네요 사람새끼가 아님~401,짐승들이네요 사람새끼가
45508,&quot;저도 층간소음 피해자입니다&quot; 소음전문 변호사가 소송 말리는 이유,2년 전,@worldclass2510Trillion,네 진짜 짐승들입니다 인간도 아닙니다\n저도 겪고 있는데 애미애비 자식새끼들\n다 ...,짐승들입니다 인간도 아닙니다 겪고 애미애비 자식새끼들 똑같애요 죽여버리고 싶습니다 ...
45509,&quot;저도 층간소음 피해자입니다&quot; 소음전문 변호사가 소송 말리는 이유,2년 전,@worldclass2510Trillion,수시로 뭔가로 찍어댑니다\n애비애미도 수시로 오르락내리락 거리고 복층에서 찍어대고 ...,수시로 뭔가로 찍어댑니다 애비애미도 수시로 오르락내리락 거리고 복층에서 찍어대고 애...
45510,&quot;저도 층간소음 피해자입니다&quot; 소음전문 변호사가 소송 말리는 이유,2년 전,@진인사대천명-t5m,​ @haeyoon2672 이사가시는게 현명한 방법입니다.,이사가시는게 현명한 방법입니다
45511,&quot;저도 층간소음 피해자입니다&quot; 소음전문 변호사가 소송 말리는 이유,3년 전,@EOh-ew2qf,@사과나무-c8v 애사진 프사로 걸어놓은것만 봐도 요즘 무개념 부모들 중 하나구...,애사진 프사로 걸어놓은것만 봐도 요즘 무개념 부모들 하나구만 아랫층 힘들거 뻔하게 ...

In [2]:
from google.colab import drive
drive.mount('/content/drive')

# 코랩 konlpy 실행
!curl -s https://raw.githubusercontent.com/teddylee777/machine-learning/master/99-Misc/01-Colab/mecab-colab.sh | bash

# Mecab 설치 후 Google Drive에 복사
!cp -r /usr/local/lib/mecab /content/drive/MyDrive/mecab
!cp -r /usr/local/etc/mecabrc /content/drive/MyDrive/mecab

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
--2026-05-26 06:23:02--  https://www.dropbox.com/s/9xls0tgtf3edgns/mecab-0.996-ko-0.9.2.tar.gz?dl=1
Resolving www.dropbox.com (www.dropbox.com)... 162.125.6.18, 2620:100:601c:18::a27d:612
Connecting to www.dropbox.com (www.dropbox.com)|162.125.6.18|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://www.dropbox.com/scl/fi/g8l6dlu5a3ebovcdymluq/mecab-0.996-ko-0.9.2.tar.gz?rlkey=xlooryouhr1l2ufqbt93ohfvy&dl=1 [following]
--2026-05-26 06:23:02--  https://www.dropbox.com/scl/fi/g8l6dlu5a3ebovcdymluq/mecab-0.996-ko-0.9.2.tar.gz?rlkey=xlooryouhr1l2ufqbt93ohfvy&dl=1
Reusing existing connection to www.dropbox.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://uc7f4054c28ba28968b59afce244.dl.dropboxusercontent.com/cd/0/inline/DBLA64W-NS29B8fBfuHbCRX_VccqbgxPh9yy-Pp_-DH9C_YCHkJQ7h40pucKLC0PjVHgxSy1DY9c0DFRQvcg4Ol9060w7D8yO6E8IRmExB6jqgijtZwdULk_edjRiAaXSlhVRUizbq09XRxSWLcn8-uH/file?dl=1# [following]
--2026-05-26 06:23:03--  https://uc7f4054c28ba28968b59afce244.dl.dropboxusercontent.com/cd/0/inline/DBLA64W-NS29B8fBfuHbCRX_VccqbgxPh9yy-Pp_-DH9C_YCHkJQ7h40pucKLC0PjVHgxSy1DY9c0DFRQvcg4Ol9060w7D8yO6E8IRmExB6jqgijtZwdULk_edjRiAaXSlhVRUizbq09XRxSWLcn8-uH/file?dl=1
Resolving uc7f4054c28ba28968b59afce244.dl.dropboxusercontent.com (uc7f4054c28ba28968b59afce244.dl.dropboxusercontent.com)... 162.125.4.15, 2620:100:601c:15::a27d:60f
Connecting to uc7f4054c28ba28968b59afce244.dl.dropboxusercontent.com (uc7f4054c28ba28968b59afce244.dl.dropboxusercontent.com)|162.125.4.15|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: /cd/0/inline2/DBL1R4YvjiaNoqWNb6oNKJo8MHvb0nSk7DFEoM1uBNPVYdTpZVsc3kR-dyDJwZfArkuhGtdxdFLAwoygDLzuThrXCmkZsp3oNOcq82NOsBK3r3F3Icwtn-DXgDfeYYxCiUkPuQG07KcL3emomiFw3nqS4xQea2lU-knoRoAqqwyvRUL3GMmETBtT5BHlfMpKfo6Ywg5h9Exl-l4VtFPJtgNmCky4qlt8LsbaasY_2m_-zBE6pHHEkPdSMv_hq2FDa6lp_XUntOpthNgniO58cp4UguiO-AKwcDINw5DhIdPY6bzgFHB_7roVZCjRLcq-DMqZ1JnuGlUg1zmrL1ggZctd1PY4E5dF_iTL2xCHCxq_RjLvSNApPmHa4kPDxFldqow/file?dl=1 [following]
--2026-05-26 06:23:03--  https://uc7f4054c28ba28968b59afce244.dl.dropboxusercontent.com/cd/0/inline2/DBL1R4YvjiaNoqWNb6oNKJo8MHvb0nSk7DFEoM1uBNPVYdTpZVsc3kR-dyDJwZfArkuhGtdxdFLAwoygDLzuThrXCmkZsp3oNOcq82NOsBK3r3F3Icwtn-DXgDfeYYxCiUkPuQG07KcL3emomiFw3nqS4xQea2lU-knoRoAqqwyvRUL3GMmETBtT5BHlfMpKfo6Ywg5h9Exl-l4VtFPJtgNmCky4qlt8LsbaasY_2m_-zBE6pHHEkPdSMv_hq2FDa6lp_XUntOpthNgniO58cp4UguiO-AKwcDINw5DhIdPY6bzgFHB_7roVZCjRLcq-DMqZ1JnuGlUg1zmrL1ggZctd1PY4E5dF_iTL2xCHCxq_RjLvSNApPmHa4kPDxFldqow/file?dl=1
Reusing existing connection to uc7f4054c28ba28968b59afce244.dl.dropboxusercontent.com:443.
HTTP request sent, awaiting response... 200 OK
Length: 1414979 (1.3M) [application/binary]
Saving to: ‘mecab-0.996-ko-0.9.2.tar.gz?dl=1’

mecab-0.996-ko-0.9. 100%[===================>]   1.35M  --.-KB/s    in 0.04s

2026-05-26 06:23:03 (35.1 MB/s) - ‘mecab-0.996-ko-0.9.2.tar.gz?dl=1’ saved [1414979/1414979]

mecab-0.996-ko-0.9.2/
mecab-0.996-ko-0.9.2/example/
mecab-0.996-ko-0.9.2/example/example.cpp
mecab-0.996-ko-0.9.2/example/example_lattice.cpp
mecab-0.996-ko-0.9.2/example/example_lattice.c
mecab-0.996-ko-0.9.2/example/example.c
mecab-0.996-ko-0.9.2/example/thread_test.cpp
mecab-0.996-ko-0.9.2/mecab-config.in
mecab-0.996-ko-0.9.2/man/
mecab-0.996-ko-0.9.2/man/Makefile.am
mecab-0.996-ko-0.9.2/man/mecab.1
mecab-0.996-ko-0.9.2/man/Makefile.in
mecab-0.996-ko-0.9.2/mecab.iss.in
mecab-0.996-ko-0.9.2/config.guess
mecab-0.996-ko-0.9.2/README
mecab-0.996-ko-0.9.2/COPYING
mecab-0.996-ko-0.9.2/CHANGES.md
mecab-0.996-ko-0.9.2/README.md
mecab-0.996-ko-0.9.2/INSTALL
mecab-0.996-ko-0.9.2/config.sub
mecab-0.996-ko-0.9.2/configure.in
mecab-0.996-ko-0.9.2/swig/
mecab-0.996-ko-0.9.2/swig/Makefile
mecab-0.996-ko-0.9.2/swig/version.h.in
mecab-0.996-ko-0.9.2/swig/version.h
mecab-0.996-ko-0.9.2/swig/MeCab.i
mecab-0.996-ko-0.9.2/aclocal.m4
mecab-0.996-ko-0.9.2/LGPL
mecab-0.996-ko-0.9.2/Makefile.am
mecab-0.996-ko-0.9.2/configure
mecab-0.996-ko-0.9.2/tests/
mecab-0.996-ko-0.9.2/tests/autolink/
mecab-0.996-ko-0.9.2/tests/autolink/unk.def
mecab-0.996-ko-0.9.2/tests/autolink/dicrc
mecab-0.996-ko-0.9.2/tests/autolink/dic.csv
mecab-0.996-ko-0.9.2/tests/autolink/test
mecab-0.996-ko-0.9.2/tests/autolink/char.def
mecab-0.996-ko-0.9.2/tests/autolink/matrix.def
mecab-0.996-ko-0.9.2/tests/autolink/test.gld
mecab-0.996-ko-0.9.2/tests/t9/
mecab-0.996-ko-0.9.2/tests/t9/unk.def
mecab-0.996-ko-0.9.2/tests/t9/ipadic.pl
mecab-0.996-ko-0.9.2/tests/t9/dicrc
mecab-0.996-ko-0.9.2/tests/t9/dic.csv
mecab-0.996-ko-0.9.2/tests/t9/test
mecab-0.996-ko-0.9.2/tests/t9/char.def
mecab-0.996-ko-0.9.2/tests/t9/matrix.def
mecab-0.996-ko-0.9.2/tests/t9/mkdic.pl
mecab-0.996-ko-0.9.2/tests/t9/test.gld
mecab-0.996-ko-0.9.2/tests/cost-train/
mecab-0.996-ko-0.9.2/tests/cost-train/ipa.train
mecab-0.996-ko-0.9.2/tests/cost-train/ipa.test
mecab-0.996-ko-0.9.2/tests/cost-train/seed/
mecab-0.996-ko-0.9.2/tests/cost-train/seed/rewrite.def
mecab-0.996-ko-0.9.2/tests/cost-train/seed/feature.def
mecab-0.996-ko-0.9.2/tests/cost-train/seed/unk.def
mecab-0.996-ko-0.9.2/tests/cost-train/seed/dicrc
mecab-0.996-ko-0.9.2/tests/cost-train/seed/dic.csv
mecab-0.996-ko-0.9.2/tests/cost-train/seed/char.def
mecab-0.996-ko-0.9.2/tests/cost-train/seed/matrix.def
mecab-0.996-ko-0.9.2/tests/run-eval.sh
mecab-0.996-ko-0.9.2/tests/run-cost-train.sh
mecab-0.996-ko-0.9.2/tests/Makefile.am
mecab-0.996-ko-0.9.2/tests/katakana/
mecab-0.996-ko-0.9.2/tests/katakana/unk.def
mecab-0.996-ko-0.9.2/tests/katakana/dicrc
mecab-0.996-ko-0.9.2/tests/katakana/dic.csv
mecab-0.996-ko-0.9.2/tests/katakana/test
mecab-0.996-ko-0.9.2/tests/katakana/char.def
mecab-0.996-ko-0.9.2/tests/katakana/matrix.def
mecab-0.996-ko-0.9.2/tests/katakana/test.gld
mecab-0.996-ko-0.9.2/tests/eval/
mecab-0.996-ko-0.9.2/tests/eval/answer
mecab-0.996-ko-0.9.2/tests/eval/system
mecab-0.996-ko-0.9.2/tests/eval/test.gld
mecab-0.996-ko-0.9.2/tests/shiin/
mecab-0.996-ko-0.9.2/tests/shiin/unk.def
mecab-0.996-ko-0.9.2/tests/shiin/dicrc
mecab-0.996-ko-0.9.2/tests/shiin/dic.csv
mecab-0.996-ko-0.9.2/tests/shiin/test
mecab-0.996-ko-0.9.2/tests/shiin/char.def
mecab-0.996-ko-0.9.2/tests/shiin/matrix.def
mecab-0.996-ko-0.9.2/tests/shiin/mkdic.pl
mecab-0.996-ko-0.9.2/tests/shiin/test.gld
mecab-0.996-ko-0.9.2/tests/latin/
mecab-0.996-ko-0.9.2/tests/latin/unk.def
mecab-0.996-ko-0.9.2/tests/latin/dicrc
mecab-0.996-ko-0.9.2/tests/latin/dic.csv
mecab-0.996-ko-0.9.2/tests/latin/test
mecab-0.996-ko-0.9.2/tests/latin/char.def
mecab-0.996-ko-0.9.2/tests/latin/matrix.def
mecab-0.996-ko-0.9.2/tests/latin/test.gld
mecab-0.996-ko-0.9.2/tests/chartype/
mecab-0.996-ko-0.9.2/tests/chartype/unk.def
mecab-0.996-ko-0.9.2/tests/chartype/dicrc
mecab-0.996-ko-0.9.2/tests/chartype/dic.csv
mecab-0.996-ko-0.9.2/tests/chartype/test
mecab-0.996-ko-0.9.2/tests/chartype/char.def
mecab-0.996-ko-0.9.2/tests/chartype/matrix.def
mecab-0.996-ko-0.9.2/tests/chartype/test.gld
mecab-0.996-ko-0.9.2/tests/run-dics.sh
mecab-0.996-ko-0.9.2/tests/ngram/
mecab-0.996-ko-0.9.2/tests/ngram/unk.def
mecab-0.996-ko-0.9.2/tests/ngram/dicrc
mecab-0.996-ko-0.9.2/tests/ngram/dic.csv
mecab-0.996-ko-0.9.2/tests/ngram/test
mecab-0.996-ko-0.9.2/tests/ngram/char.def
mecab-0.996-ko-0.9.2/tests/ngram/matrix.def
mecab-0.996-ko-0.9.2/tests/ngram/test.gld
mecab-0.996-ko-0.9.2/tests/Makefile.in
mecab-0.996-ko-0.9.2/ltmain.sh
mecab-0.996-ko-0.9.2/config.rpath
mecab-0.996-ko-0.9.2/config.h.in
mecab-0.996-ko-0.9.2/mecabrc.in
mecab-0.996-ko-0.9.2/GPL
mecab-0.996-ko-0.9.2/Makefile.train
mecab-0.996-ko-0.9.2/ChangeLog
mecab-0.996-ko-0.9.2/install-sh
mecab-0.996-ko-0.9.2/AUTHORS
mecab-0.996-ko-0.9.2/doc/
mecab-0.996-ko-0.9.2/doc/bindings.html
mecab-0.996-ko-0.9.2/doc/posid.html
mecab-0.996-ko-0.9.2/doc/unk.html
mecab-0.996-ko-0.9.2/doc/learn.html
mecab-0.996-ko-0.9.2/doc/format.html
mecab-0.996-ko-0.9.2/doc/libmecab.html
mecab-0.996-ko-0.9.2/doc/mecab.css
mecab-0.996-ko-0.9.2/doc/feature.html
mecab-0.996-ko-0.9.2/doc/Makefile.am
mecab-0.996-ko-0.9.2/doc/soft.html
mecab-0.996-ko-0.9.2/doc/en/
mecab-0.996-ko-0.9.2/doc/en/bindings.html
mecab-0.996-ko-0.9.2/doc/dic-detail.html
mecab-0.996-ko-0.9.2/doc/flow.png
mecab-0.996-ko-0.9.2/doc/mecab.html
mecab-0.996-ko-0.9.2/doc/index.html
mecab-0.996-ko-0.9.2/doc/result.png
mecab-0.996-ko-0.9.2/doc/doxygen/
mecab-0.996-ko-0.9.2/doc/doxygen/tab_a.png
mecab-0.996-ko-0.9.2/doc/doxygen/globals_eval.html
mecab-0.996-ko-0.9.2/doc/doxygen/classMeCab_1_1Tagger-members.html
mecab-0.996-ko-0.9.2/doc/doxygen/functions_vars.html
mecab-0.996-ko-0.9.2/doc/doxygen/doxygen.css
mecab-0.996-ko-0.9.2/doc/doxygen/tab_r.gif
mecab-0.996-ko-0.9.2/doc/doxygen/classMeCab_1_1Lattice.html
mecab-0.996-ko-0.9.2/doc/doxygen/functions.html
mecab-0.996-ko-0.9.2/doc/doxygen/classMeCab_1_1Tagger.html
mecab-0.996-ko-0.9.2/doc/doxygen/mecab_8h_source.html
mecab-0.996-ko-0.9.2/doc/doxygen/tabs.css
mecab-0.996-ko-0.9.2/doc/doxygen/nav_f.png
mecab-0.996-ko-0.9.2/doc/doxygen/tab_b.png
mecab-0.996-ko-0.9.2/doc/doxygen/globals.html
mecab-0.996-ko-0.9.2/doc/doxygen/nav_h.png
mecab-0.996-ko-0.9.2/doc/doxygen/tab_h.png
mecab-0.996-ko-0.9.2/doc/doxygen/classMeCab_1_1Model.html
mecab-0.996-ko-0.9.2/doc/doxygen/globals_func.html
mecab-0.996-ko-0.9.2/doc/doxygen/closed.png
mecab-0.996-ko-0.9.2/doc/doxygen/tab_l.gif
mecab-0.996-ko-0.9.2/doc/doxygen/structmecab__path__t-members.html
mecab-0.996-ko-0.9.2/doc/doxygen/functions_func.html
mecab-0.996-ko-0.9.2/doc/doxygen/globals_type.html
mecab-0.996-ko-0.9.2/doc/doxygen/classMeCab_1_1Lattice-members.html
mecab-0.996-ko-0.9.2/doc/doxygen/structmecab__node__t.html
mecab-0.996-ko-0.9.2/doc/doxygen/namespacemembers_func.html
mecab-0.996-ko-0.9.2/doc/doxygen/tab_s.png
mecab-0.996-ko-0.9.2/doc/doxygen/structmecab__dictionary__info__t-members.html
mecab-0.996-ko-0.9.2/doc/doxygen/namespacemembers_type.html
mecab-0.996-ko-0.9.2/doc/doxygen/classMeCab_1_1Model-members.html
mecab-0.996-ko-0.9.2/doc/doxygen/structmecab__dictionary__info__t.html
mecab-0.996-ko-0.9.2/doc/doxygen/namespaces.html
mecab-0.996-ko-0.9.2/doc/doxygen/namespacemembers.html
mecab-0.996-ko-0.9.2/doc/doxygen/namespaceMeCab.html
mecab-0.996-ko-0.9.2/doc/doxygen/structmecab__path__t.html
mecab-0.996-ko-0.9.2/doc/doxygen/files.html
mecab-0.996-ko-0.9.2/doc/doxygen/structmecab__node__t-members.html
mecab-0.996-ko-0.9.2/doc/doxygen/index.html
mecab-0.996-ko-0.9.2/doc/doxygen/annotated.html
mecab-0.996-ko-0.9.2/doc/doxygen/globals_defs.html
mecab-0.996-ko-0.9.2/doc/doxygen/classes.html
mecab-0.996-ko-0.9.2/doc/doxygen/mecab_8h-source.html
mecab-0.996-ko-0.9.2/doc/doxygen/doxygen.png
mecab-0.996-ko-0.9.2/doc/doxygen/tab_b.gif
mecab-0.996-ko-0.9.2/doc/doxygen/bc_s.png
mecab-0.996-ko-0.9.2/doc/doxygen/open.png
mecab-0.996-ko-0.9.2/doc/doxygen/mecab_8h.html
mecab-0.996-ko-0.9.2/doc/dic.html
mecab-0.996-ko-0.9.2/doc/partial.html
mecab-0.996-ko-0.9.2/doc/feature.png
mecab-0.996-ko-0.9.2/doc/Makefile.in
mecab-0.996-ko-0.9.2/missing
mecab-0.996-ko-0.9.2/BSD
mecab-0.996-ko-0.9.2/NEWS
mecab-0.996-ko-0.9.2/mkinstalldirs
mecab-0.996-ko-0.9.2/src/
mecab-0.996-ko-0.9.2/src/dictionary.h
mecab-0.996-ko-0.9.2/src/writer.h
mecab-0.996-ko-0.9.2/src/utils.h
mecab-0.996-ko-0.9.2/src/string_buffer.cpp
mecab-0.996-ko-0.9.2/src/tokenizer.cpp
mecab-0.996-ko-0.9.2/src/make.bat
mecab-0.996-ko-0.9.2/src/mecab.h
mecab-0.996-ko-0.9.2/src/freelist.h
mecab-0.996-ko-0.9.2/src/string_buffer.h
mecab-0.996-ko-0.9.2/src/learner_tagger.h
mecab-0.996-ko-0.9.2/src/dictionary_compiler.cpp
mecab-0.996-ko-0.9.2/src/eval.cpp
mecab-0.996-ko-0.9.2/src/mecab-system-eval.cpp
mecab-0.996-ko-0.9.2/src/darts.h
mecab-0.996-ko-0.9.2/src/param.h
mecab-0.996-ko-0.9.2/src/char_property.h
mecab-0.996-ko-0.9.2/src/learner_node.h
mecab-0.996-ko-0.9.2/src/mecab-dict-gen.cpp
mecab-0.996-ko-0.9.2/src/mecab-dict-index.cpp
mecab-0.996-ko-0.9.2/src/winmain.h
mecab-0.996-ko-0.9.2/src/thread.h
mecab-0.996-ko-0.9.2/src/context_id.cpp
mecab-0.996-ko-0.9.2/src/Makefile.am
mecab-0.996-ko-0.9.2/src/connector.h
mecab-0.996-ko-0.9.2/src/common.h
mecab-0.996-ko-0.9.2/src/dictionary_rewriter.cpp
mecab-0.996-ko-0.9.2/src/Makefile.msvc.in
mecab-0.996-ko-0.9.2/src/dictionary_rewriter.h
mecab-0.996-ko-0.9.2/src/feature_index.h
mecab-0.996-ko-0.9.2/src/iconv_utils.cpp
mecab-0.996-ko-0.9.2/src/char_property.cpp
mecab-0.996-ko-0.9.2/src/mecab-test-gen.cpp
mecab-0.996-ko-0.9.2/src/tagger.cpp
mecab-0.996-ko-0.9.2/src/mecab-cost-train.cpp
mecab-0.996-ko-0.9.2/src/learner.cpp
mecab-0.996-ko-0.9.2/src/dictionary.cpp
mecab-0.996-ko-0.9.2/src/lbfgs.cpp
mecab-0.996-ko-0.9.2/src/ucs.h
mecab-0.996-ko-0.9.2/src/writer.cpp
mecab-0.996-ko-0.9.2/src/learner_tagger.cpp
mecab-0.996-ko-0.9.2/src/lbfgs.h
mecab-0.996-ko-0.9.2/src/libmecab.cpp
mecab-0.996-ko-0.9.2/src/tokenizer.h
mecab-0.996-ko-0.9.2/src/mecab.cpp
mecab-0.996-ko-0.9.2/src/utils.cpp
mecab-0.996-ko-0.9.2/src/dictionary_generator.cpp
mecab-0.996-ko-0.9.2/src/param.cpp
mecab-0.996-ko-0.9.2/src/context_id.h
mecab-0.996-ko-0.9.2/src/mmap.h
mecab-0.996-ko-0.9.2/src/viterbi.h
mecab-0.996-ko-0.9.2/src/viterbi.cpp
mecab-0.996-ko-0.9.2/src/stream_wrapper.h
mecab-0.996-ko-0.9.2/src/feature_index.cpp
mecab-0.996-ko-0.9.2/src/nbest_generator.h
mecab-0.996-ko-0.9.2/src/ucstable.h
mecab-0.996-ko-0.9.2/src/nbest_generator.cpp
mecab-0.996-ko-0.9.2/src/iconv_utils.h
mecab-0.996-ko-0.9.2/src/connector.cpp
mecab-0.996-ko-0.9.2/src/Makefile.in
mecab-0.996-ko-0.9.2/src/scoped_ptr.h
mecab-0.996-ko-0.9.2/Makefile.in
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for style of include used by make... GNU
checking dependency style of gcc... none
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... none
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking whether gcc needs -traditional... no
checking whether make sets $(MAKE)... (cached) yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /usr/bin/sed
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... dlltool
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for mt... no
checking if : is a manifest tool... no
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /usr/bin/ld -m elf_x86_64
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking for g++ option to produce PIC... -fPIC -DPIC
checking if g++ PIC flag -fPIC -DPIC works... yes
checking if g++ static flag -static works... yes
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking for library containing strerror... none required
checking whether byte ordering is bigendian... no
checking for ld used by GCC... /usr/bin/ld -m elf_x86_64
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
checking for shared library run path origin... done
checking for iconv... yes
checking for working iconv... yes
checking for iconv declaration...
         extern size_t iconv (iconv_t cd, char * *inbuf, size_t *inbytesleft, char * *outbuf, size_t *outbytesleft);
checking for ANSI C header files... (cached) yes
checking for an ANSI C-conforming const... yes
checking whether byte ordering is bigendian... (cached) no
checking for string.h... (cached) yes
checking for stdlib.h... (cached) yes
checking for unistd.h... (cached) yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking for stdint.h... (cached) yes
checking for sys/stat.h... (cached) yes
checking sys/mman.h usability... yes
checking sys/mman.h presence... yes
checking for sys/mman.h... yes
checking sys/times.h usability... yes
checking sys/times.h presence... yes
checking for sys/times.h... yes
checking for sys/types.h... (cached) yes
checking dirent.h usability... yes
checking dirent.h presence... yes
checking for dirent.h... yes
checking ctype.h usability... yes
checking ctype.h presence... yes
checking for ctype.h... yes
checking for sys/types.h... (cached) yes
checking io.h usability... no
checking io.h presence... no
checking for io.h... no
checking windows.h usability... no
checking windows.h presence... no
checking for windows.h... no
checking pthread.h usability... yes
checking pthread.h presence... yes
checking for pthread.h... yes
checking for off_t... yes
checking for size_t... yes
checking size of char... 1
checking size of short... 2
checking size of int... 4
checking size of long... 8
checking size of long long... 8
checking size of size_t... 8
checking for size_t... (cached) yes

In [3]:
! pip install kiwipiepy
import pandas as pd
import re
from konlpy.tag import Okt
from kiwipiepy import Kiwi

Collecting kiwipiepy
  Downloading kiwipiepy-0.23.1-cp39-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.3 kB)
Collecting kiwipiepy_model<0.24,>=0.23 (from kiwipiepy)
  Downloading kiwipiepy_model-0.23.0.tar.gz (88.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 88.0/88.0 MB 7.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from kiwipiepy) (2.0.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from kiwipiepy) (4.67.3)
Downloading kiwipiepy-0.23.1-cp39-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (6.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.3/6.3 MB 20.7 MB/s eta 0:00:00
Building wheels for collected packages: kiwipiepy_model
  Building wheel for kiwipiepy_model (setup.py) ... done
  Created wheel for kiwipiepy_model: filename=kiwipiepy_model-0.23.0-py3-none-any.whl size=88067826 sha256=0cbbfcd2bb20559abfd4b95dc9c4ad1954df5b9334661af5482e13fd35aa84bc
  Stored in directory: /root/.cache/pip/wheels/f2/94/da/ff88b4c2305cd1f3effc8001b5f42f16dc9931bcd84d1e77c3
Successfully built kiwipiepy_model
Installing collected packages: kiwipiepy_model, kiwipiepy
Successfully installed kiwipiepy-0.23.1 kiwipiepy_model-0.23.0

# 20자 이하 삭제

In [6]:
import pandas as pd

# contents_clean 열의 길이가 20자 초과인 행만 선택하여 다시 저장
df = df[df['contents_clean'].str.len() > 22]

In [7]:
df

,title,date,author,contents,contents_clean
2,엘베 안 흉기에 40차례…층간 소음 가해? &quot;억울해&quot; / JTBC...,57분 전,@김나스-k9r,가족들 그엘베 타는거 진짜 고역이겠다.. 어떻게 사냐 진짜,가족들 그엘베 타는거 고역이겠다 어떻게 사냐
6,엘베 안 흉기에 40차례…층간 소음 가해? &quot;억울해&quot; / JTBC...,2시간 전,@사라로asf,엘베에서 저도 층간소음으로 다툰적이 있어요\n전세벽에 세탁기를 맬 돌리시더라구요,엘베에서 층간소음으로 다툰적이 전세벽에 세탁기를 돌리시더라구요
7,엘베 안 흉기에 40차례…층간 소음 가해? &quot;억울해&quot; / JTBC...,2시간 전,@가린마-b1t,서대구역 7 구역 이라고 들었는데 7단지인지 정확히는 잘모르겠지만 부실공사에 제값...,서대구역 구역 이라고 들었는데 단지인지 정확히는 잘모르겠지만 부실공사에 제값보다 고...
8,엘베 안 흉기에 40차례…층간 소음 가해? &quot;억울해&quot; / JTBC...,2시간 전,@dongwonkim1223,아파트 층간소음 불만충들. 나무아파트에서 강제로 1달 살게 하기 법을 만듭시다.,아파트 층간소음 불만충들 나무아파트에서 강제로 살게 하기 법을 만듭시다
9,엘베 안 흉기에 40차례…층간 소음 가해? &quot;억울해&quot; / JTBC...,2시간 전(수정됨),@김혜정-l8c,정신병자를 이웃으로만난게 불운이였다ㅜㅜ\n조현병같은데 왜 그냥 둔거야,정신병자를 이웃으로만난게 불운이였다 조현병같은데 둔거야
...,...,...,...,...,...
45502,&quot;저도 층간소음 피해자입니다&quot; 소음전문 변호사가 소송 말리는 이유,3년 전(수정됨),@Ji-P,@김빠빠-j2k 진짜 저도 딱 이 심정... \n난 그래도 이분에 비하면 다행인...,심정 이분에 비하면 다행인게 새벽 정도면 자서 그런가 조용해지는데 현재 추석이고 코...
45505,&quot;저도 층간소음 피해자입니다&quot; 소음전문 변호사가 소송 말리는 이유,1년 전,@진리-l3w,난 옆집이 존나 시끄럽던대요 코콜이 소리까지 다 들림,옆집이 존나 시끄럽던대요 코콜이 소리까지 들림
45508,&quot;저도 층간소음 피해자입니다&quot; 소음전문 변호사가 소송 말리는 이유,2년 전,@worldclass2510Trillion,네 진짜 짐승들입니다 인간도 아닙니다\n저도 겪고 있는데 애미애비 자식새끼들\n다 ...,짐승들입니다 인간도 아닙니다 겪고 애미애비 자식새끼들 똑같애요 죽여버리고 싶습니다 ...
45509,&quot;저도 층간소음 피해자입니다&quot; 소음전문 변호사가 소송 말리는 이유,2년 전,@worldclass2510Trillion,수시로 뭔가로 찍어댑니다\n애비애미도 수시로 오르락내리락 거리고 복층에서 찍어대고 ...,수시로 뭔가로 찍어댑니다 애비애미도 수시로 오르락내리락 거리고 복층에서 찍어대고 애...
45511,&quot;저도 층간소음 피해자입니다&quot; 소음전문 변호사가 소송 말리는 이유,3년 전,@EOh-ew2qf,@사과나무-c8v 애사진 프사로 걸어놓은것만 봐도 요즘 무개념 부모들 중 하나구...,애사진 프사로 걸어놓은것만 봐도 요즘 무개념 부모들 하나구만 아랫층 힘들거 뻔하게 ...

# 중복글 제거

In [8]:
df["contents_clean"].duplicated()
df.drop_duplicates("contents_clean")

,title,date,author,contents,contents_clean
2,엘베 안 흉기에 40차례…층간 소음 가해? &quot;억울해&quot; / JTBC...,57분 전,@김나스-k9r,가족들 그엘베 타는거 진짜 고역이겠다.. 어떻게 사냐 진짜,가족들 그엘베 타는거 고역이겠다 어떻게 사냐
6,엘베 안 흉기에 40차례…층간 소음 가해? &quot;억울해&quot; / JTBC...,2시간 전,@사라로asf,엘베에서 저도 층간소음으로 다툰적이 있어요\n전세벽에 세탁기를 맬 돌리시더라구요,엘베에서 층간소음으로 다툰적이 전세벽에 세탁기를 돌리시더라구요
7,엘베 안 흉기에 40차례…층간 소음 가해? &quot;억울해&quot; / JTBC...,2시간 전,@가린마-b1t,서대구역 7 구역 이라고 들었는데 7단지인지 정확히는 잘모르겠지만 부실공사에 제값...,서대구역 구역 이라고 들었는데 단지인지 정확히는 잘모르겠지만 부실공사에 제값보다 고...
8,엘베 안 흉기에 40차례…층간 소음 가해? &quot;억울해&quot; / JTBC...,2시간 전,@dongwonkim1223,아파트 층간소음 불만충들. 나무아파트에서 강제로 1달 살게 하기 법을 만듭시다.,아파트 층간소음 불만충들 나무아파트에서 강제로 살게 하기 법을 만듭시다
9,엘베 안 흉기에 40차례…층간 소음 가해? &quot;억울해&quot; / JTBC...,2시간 전(수정됨),@김혜정-l8c,정신병자를 이웃으로만난게 불운이였다ㅜㅜ\n조현병같은데 왜 그냥 둔거야,정신병자를 이웃으로만난게 불운이였다 조현병같은데 둔거야
...,...,...,...,...,...
45502,&quot;저도 층간소음 피해자입니다&quot; 소음전문 변호사가 소송 말리는 이유,3년 전(수정됨),@Ji-P,@김빠빠-j2k 진짜 저도 딱 이 심정... \n난 그래도 이분에 비하면 다행인...,심정 이분에 비하면 다행인게 새벽 정도면 자서 그런가 조용해지는데 현재 추석이고 코...
45505,&quot;저도 층간소음 피해자입니다&quot; 소음전문 변호사가 소송 말리는 이유,1년 전,@진리-l3w,난 옆집이 존나 시끄럽던대요 코콜이 소리까지 다 들림,옆집이 존나 시끄럽던대요 코콜이 소리까지 들림
45508,&quot;저도 층간소음 피해자입니다&quot; 소음전문 변호사가 소송 말리는 이유,2년 전,@worldclass2510Trillion,네 진짜 짐승들입니다 인간도 아닙니다\n저도 겪고 있는데 애미애비 자식새끼들\n다 ...,짐승들입니다 인간도 아닙니다 겪고 애미애비 자식새끼들 똑같애요 죽여버리고 싶습니다 ...
45509,&quot;저도 층간소음 피해자입니다&quot; 소음전문 변호사가 소송 말리는 이유,2년 전,@worldclass2510Trillion,수시로 뭔가로 찍어댑니다\n애비애미도 수시로 오르락내리락 거리고 복층에서 찍어대고 ...,수시로 뭔가로 찍어댑니다 애비애미도 수시로 오르락내리락 거리고 복층에서 찍어대고 애...
45511,&quot;저도 층간소음 피해자입니다&quot; 소음전문 변호사가 소송 말리는 이유,3년 전,@EOh-ew2qf,@사과나무-c8v 애사진 프사로 걸어놓은것만 봐도 요즘 무개념 부모들 중 하나구...,애사진 프사로 걸어놓은것만 봐도 요즘 무개념 부모들 하나구만 아랫층 힘들거 뻔하게 ...

# 대소문자 통일

In [9]:
df["contents_clean"] = df["contents_clean"].apply(lambda x : x.lower())
df

/tmp/ipykernel_1570/3534833996.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["contents_clean"] = df["contents_clean"].apply(lambda x : x.lower())

,title,date,author,contents,contents_clean
2,엘베 안 흉기에 40차례…층간 소음 가해? &quot;억울해&quot; / JTBC...,57분 전,@김나스-k9r,가족들 그엘베 타는거 진짜 고역이겠다.. 어떻게 사냐 진짜,가족들 그엘베 타는거 고역이겠다 어떻게 사냐
6,엘베 안 흉기에 40차례…층간 소음 가해? &quot;억울해&quot; / JTBC...,2시간 전,@사라로asf,엘베에서 저도 층간소음으로 다툰적이 있어요\n전세벽에 세탁기를 맬 돌리시더라구요,엘베에서 층간소음으로 다툰적이 전세벽에 세탁기를 돌리시더라구요
7,엘베 안 흉기에 40차례…층간 소음 가해? &quot;억울해&quot; / JTBC...,2시간 전,@가린마-b1t,서대구역 7 구역 이라고 들었는데 7단지인지 정확히는 잘모르겠지만 부실공사에 제값...,서대구역 구역 이라고 들었는데 단지인지 정확히는 잘모르겠지만 부실공사에 제값보다 고...
8,엘베 안 흉기에 40차례…층간 소음 가해? &quot;억울해&quot; / JTBC...,2시간 전,@dongwonkim1223,아파트 층간소음 불만충들. 나무아파트에서 강제로 1달 살게 하기 법을 만듭시다.,아파트 층간소음 불만충들 나무아파트에서 강제로 살게 하기 법을 만듭시다
9,엘베 안 흉기에 40차례…층간 소음 가해? &quot;억울해&quot; / JTBC...,2시간 전(수정됨),@김혜정-l8c,정신병자를 이웃으로만난게 불운이였다ㅜㅜ\n조현병같은데 왜 그냥 둔거야,정신병자를 이웃으로만난게 불운이였다 조현병같은데 둔거야
...,...,...,...,...,...
45502,&quot;저도 층간소음 피해자입니다&quot; 소음전문 변호사가 소송 말리는 이유,3년 전(수정됨),@Ji-P,@김빠빠-j2k 진짜 저도 딱 이 심정... \n난 그래도 이분에 비하면 다행인...,심정 이분에 비하면 다행인게 새벽 정도면 자서 그런가 조용해지는데 현재 추석이고 코...
45505,&quot;저도 층간소음 피해자입니다&quot; 소음전문 변호사가 소송 말리는 이유,1년 전,@진리-l3w,난 옆집이 존나 시끄럽던대요 코콜이 소리까지 다 들림,옆집이 존나 시끄럽던대요 코콜이 소리까지 들림
45508,&quot;저도 층간소음 피해자입니다&quot; 소음전문 변호사가 소송 말리는 이유,2년 전,@worldclass2510Trillion,네 진짜 짐승들입니다 인간도 아닙니다\n저도 겪고 있는데 애미애비 자식새끼들\n다 ...,짐승들입니다 인간도 아닙니다 겪고 애미애비 자식새끼들 똑같애요 죽여버리고 싶습니다 ...
45509,&quot;저도 층간소음 피해자입니다&quot; 소음전문 변호사가 소송 말리는 이유,2년 전,@worldclass2510Trillion,수시로 뭔가로 찍어댑니다\n애비애미도 수시로 오르락내리락 거리고 복층에서 찍어대고 ...,수시로 뭔가로 찍어댑니다 애비애미도 수시로 오르락내리락 거리고 복층에서 찍어대고 애...
45511,&quot;저도 층간소음 피해자입니다&quot; 소음전문 변호사가 소송 말리는 이유,3년 전,@EOh-ew2qf,@사과나무-c8v 애사진 프사로 걸어놓은것만 봐도 요즘 무개념 부모들 중 하나구...,애사진 프사로 걸어놓은것만 봐도 요즘 무개념 부모들 하나구만 아랫층 힘들거 뻔하게 ...

# 토크나이징

In [12]:
okt = Okt()
df["token"] = df["contents_clean"].apply(lambda x : okt.morphs(x, stem = True, norm = True))
df

/tmp/ipykernel_1570/3403184620.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["token"] = df["contents_clean"].apply(lambda x : okt.morphs(x, stem = True, norm = True))

,title,date,author,contents,contents_clean,token
2,엘베 안 흉기에 40차례…층간 소음 가해? &quot;억울해&quot; / JTBC...,57분 전,@김나스-k9r,가족들 그엘베 타는거 진짜 고역이겠다.. 어떻게 사냐 진짜,가족들 그엘베 타는거 고역이겠다 어떻게 사냐,"[가족, 들, 그, 엘베, 타다, 고역, 이, 겠다, 어떻다, 사다]"
6,엘베 안 흉기에 40차례…층간 소음 가해? &quot;억울해&quot; / JTBC...,2시간 전,@사라로asf,엘베에서 저도 층간소음으로 다툰적이 있어요\n전세벽에 세탁기를 맬 돌리시더라구요,엘베에서 층간소음으로 다툰적이 전세벽에 세탁기를 돌리시더라구요,"[엘베, 에서, 층간소음, 으로, 다투다, 적, 이, 전, 세, 벽, 에, 세탁기,..."
7,엘베 안 흉기에 40차례…층간 소음 가해? &quot;억울해&quot; / JTBC...,2시간 전,@가린마-b1t,서대구역 7 구역 이라고 들었는데 7단지인지 정확히는 잘모르겠지만 부실공사에 제값...,서대구역 구역 이라고 들었는데 단지인지 정확히는 잘모르겠지만 부실공사에 제값보다 고...,"[서대구역, 구역, 이라고, 들다, 단지, 인지, 정확하다, 잘, 모르다, 부실, ..."
8,엘베 안 흉기에 40차례…층간 소음 가해? &quot;억울해&quot; / JTBC...,2시간 전,@dongwonkim1223,아파트 층간소음 불만충들. 나무아파트에서 강제로 1달 살게 하기 법을 만듭시다.,아파트 층간소음 불만충들 나무아파트에서 강제로 살게 하기 법을 만듭시다,"[아파트, 층간소음, 불만, 충, 들, 나무, 아파트, 에서, 강제, 로, 살, 게..."
9,엘베 안 흉기에 40차례…층간 소음 가해? &quot;억울해&quot; / JTBC...,2시간 전(수정됨),@김혜정-l8c,정신병자를 이웃으로만난게 불운이였다ㅜㅜ\n조현병같은데 왜 그냥 둔거야,정신병자를 이웃으로만난게 불운이였다 조현병같은데 둔거야,"[정신병, 자, 를, 이웃, 으로만, 난, 게, 불다, 조현병, 같다, 두다]"
...,...,...,...,...,...,...
45502,&quot;저도 층간소음 피해자입니다&quot; 소음전문 변호사가 소송 말리는 이유,3년 전(수정됨),@Ji-P,@김빠빠-j2k 진짜 저도 딱 이 심정... \n난 그래도 이분에 비하면 다행인...,심정 이분에 비하면 다행인게 새벽 정도면 자서 그런가 조용해지는데 현재 추석이고 코...,"[심정, 이분, 에, 비, 하다, 다행, 인게, 새벽, 정도, 면, 자서, 그, 런..."
45505,&quot;저도 층간소음 피해자입니다&quot; 소음전문 변호사가 소송 말리는 이유,1년 전,@진리-l3w,난 옆집이 존나 시끄럽던대요 코콜이 소리까지 다 들림,옆집이 존나 시끄럽던대요 코콜이 소리까지 들림,"[옆집, 이, 존나, 시끄럽다, 대요, 코콜, 이, 소리, 까지, 들리다]"
45508,&quot;저도 층간소음 피해자입니다&quot; 소음전문 변호사가 소송 말리는 이유,2년 전,@worldclass2510Trillion,네 진짜 짐승들입니다 인간도 아닙니다\n저도 겪고 있는데 애미애비 자식새끼들\n다 ...,짐승들입니다 인간도 아닙니다 겪고 애미애비 자식새끼들 똑같애요 죽여버리고 싶습니다 ...,"[짐승, 들이다, 인간, 도, 아니다, 겪다, 애, 미애, 비, 자식새끼, 들, 똑..."
45509,&quot;저도 층간소음 피해자입니다&quot; 소음전문 변호사가 소송 말리는 이유,2년 전,@worldclass2510Trillion,수시로 뭔가로 찍어댑니다\n애비애미도 수시로 오르락내리락 거리고 복층에서 찍어대고 ...,수시로 뭔가로 찍어댑니다 애비애미도 수시로 오르락내리락 거리고 복층에서 찍어대고 애...,"[수시로, 뭔가, 로, 찍다, 대다, 애비, 애, 미도, 수시로, 오르락내리락, 거..."
45511,&quot;저도 층간소음 피해자입니다&quot; 소음전문 변호사가 소송 말리는 이유,3년 전,@EOh-ew2qf,@사과나무-c8v 애사진 프사로 걸어놓은것만 봐도 요즘 무개념 부모들 중 하나구...,애사진 프사로 걸어놓은것만 봐도 요즘 무개념 부모들 하나구만 아랫층 힘들거 뻔하게 ...,"[애, 사진, 프사, 로, 걸다, 것, 만, 보다, 요즘, 무, 개념, 부모, 들,..."

In [13]:
from tqdm import tqdm

okt = Okt()
tqdm.pandas()

def extract_pos(text, pos):
  left=[]
  for i in okt.pos(text,stem=True, norm =True):  # i 가 하나의 튜플 형성
    if i[1] in pos:   # 만약 i의 첫번째 원소가 명사 동사 형용사라면,
      left.append(i[0])
  return left

df["token"] = df["contents_clean"].progress_apply(lambda x : extract_pos(x, ["Noun", "Verb", "Adjective"]))
df

100%|██████████| 23102/23102 [03:50<00:00, 100.39it/s]
/tmp/ipykernel_1570/3669641099.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["token"] = df["contents_clean"].progress_apply(lambda x : extract_pos(x, ["Noun", "Verb", "Adjective"]))

,title,date,author,contents,contents_clean,token
2,엘베 안 흉기에 40차례…층간 소음 가해? &quot;억울해&quot; / JTBC...,57분 전,@김나스-k9r,가족들 그엘베 타는거 진짜 고역이겠다.. 어떻게 사냐 진짜,가족들 그엘베 타는거 고역이겠다 어떻게 사냐,"[가족, 엘베, 타다, 고역, 겠다, 어떻다, 사다]"
6,엘베 안 흉기에 40차례…층간 소음 가해? &quot;억울해&quot; / JTBC...,2시간 전,@사라로asf,엘베에서 저도 층간소음으로 다툰적이 있어요\n전세벽에 세탁기를 맬 돌리시더라구요,엘베에서 층간소음으로 다툰적이 전세벽에 세탁기를 돌리시더라구요,"[엘베, 층간소음, 다투다, 적, 벽, 세탁기, 돌리다]"
7,엘베 안 흉기에 40차례…층간 소음 가해? &quot;억울해&quot; / JTBC...,2시간 전,@가린마-b1t,서대구역 7 구역 이라고 들었는데 7단지인지 정확히는 잘모르겠지만 부실공사에 제값...,서대구역 구역 이라고 들었는데 단지인지 정확히는 잘모르겠지만 부실공사에 제값보다 고...,"[서대구역, 구역, 들다, 단지, 정확하다, 모르다, 부실, 공사, 값, 평가, 되..."
8,엘베 안 흉기에 40차례…층간 소음 가해? &quot;억울해&quot; / JTBC...,2시간 전,@dongwonkim1223,아파트 층간소음 불만충들. 나무아파트에서 강제로 1달 살게 하기 법을 만듭시다.,아파트 층간소음 불만충들 나무아파트에서 강제로 살게 하기 법을 만듭시다,"[아파트, 층간소음, 불만, 충, 나무, 아파트, 강제, 살, 하다, 법, 만듭시]"
9,엘베 안 흉기에 40차례…층간 소음 가해? &quot;억울해&quot; / JTBC...,2시간 전(수정됨),@김혜정-l8c,정신병자를 이웃으로만난게 불운이였다ㅜㅜ\n조현병같은데 왜 그냥 둔거야,정신병자를 이웃으로만난게 불운이였다 조현병같은데 둔거야,"[정신병, 이웃, 난, 불다, 조현병, 같다, 두다]"
...,...,...,...,...,...,...
45502,&quot;저도 층간소음 피해자입니다&quot; 소음전문 변호사가 소송 말리는 이유,3년 전(수정됨),@Ji-P,@김빠빠-j2k 진짜 저도 딱 이 심정... \n난 그래도 이분에 비하면 다행인...,심정 이분에 비하면 다행인게 새벽 정도면 자서 그런가 조용해지는데 현재 추석이고 코...,"[심정, 이분, 비, 하다, 다행, 새벽, 정도, 자서, 런가, 조용하다, 현재, ..."
45505,&quot;저도 층간소음 피해자입니다&quot; 소음전문 변호사가 소송 말리는 이유,1년 전,@진리-l3w,난 옆집이 존나 시끄럽던대요 코콜이 소리까지 다 들림,옆집이 존나 시끄럽던대요 코콜이 소리까지 들림,"[옆집, 존나, 시끄럽다, 대요, 코콜, 소리, 들리다]"
45508,&quot;저도 층간소음 피해자입니다&quot; 소음전문 변호사가 소송 말리는 이유,2년 전,@worldclass2510Trillion,네 진짜 짐승들입니다 인간도 아닙니다\n저도 겪고 있는데 애미애비 자식새끼들\n다 ...,짐승들입니다 인간도 아닙니다 겪고 애미애비 자식새끼들 똑같애요 죽여버리고 싶습니다 ...,"[짐승, 들이다, 인간, 아니다, 겪다, 애, 미애, 비, 자식새끼, 똑같다, 애,..."
45509,&quot;저도 층간소음 피해자입니다&quot; 소음전문 변호사가 소송 말리는 이유,2년 전,@worldclass2510Trillion,수시로 뭔가로 찍어댑니다\n애비애미도 수시로 오르락내리락 거리고 복층에서 찍어대고 ...,수시로 뭔가로 찍어댑니다 애비애미도 수시로 오르락내리락 거리고 복층에서 찍어대고 애...,"[뭔가, 찍다, 대다, 애비, 애, 미도, 오르락내리락, 거리, 복층, 찍다, 대고..."
45511,&quot;저도 층간소음 피해자입니다&quot; 소음전문 변호사가 소송 말리는 이유,3년 전,@EOh-ew2qf,@사과나무-c8v 애사진 프사로 걸어놓은것만 봐도 요즘 무개념 부모들 중 하나구...,애사진 프사로 걸어놓은것만 봐도 요즘 무개념 부모들 하나구만 아랫층 힘들거 뻔하게 ...,"[애, 사진, 프사, 걸다, 것, 보다, 요즘, 무, 개념, 부모, 하나, 구만, ..."

# 불용어 제거

In [14]:
from kiwipiepy.utils import Stopwords

stopwords = Stopwords()
sw = set([i[0] for i in stopwords.stopwords]) # 중복 제거 위해 set 사용

cleaned_token = []
for i in df["token"]:
  imsi = []
  for w in i:
    if w not in sw:
      imsi.append(w)
  cleaned_token.append(imsi)
df["token"] = cleaned_token
df

/tmp/ipykernel_1570/2942863180.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["token"] = cleaned_token

,title,date,author,contents,contents_clean,token
2,엘베 안 흉기에 40차례…층간 소음 가해? &quot;억울해&quot; / JTBC...,57분 전,@김나스-k9r,가족들 그엘베 타는거 진짜 고역이겠다.. 어떻게 사냐 진짜,가족들 그엘베 타는거 고역이겠다 어떻게 사냐,"[가족, 엘베, 타다, 고역, 겠다, 어떻다, 사다]"
6,엘베 안 흉기에 40차례…층간 소음 가해? &quot;억울해&quot; / JTBC...,2시간 전,@사라로asf,엘베에서 저도 층간소음으로 다툰적이 있어요\n전세벽에 세탁기를 맬 돌리시더라구요,엘베에서 층간소음으로 다툰적이 전세벽에 세탁기를 돌리시더라구요,"[엘베, 층간소음, 다투다, 벽, 세탁기, 돌리다]"
7,엘베 안 흉기에 40차례…층간 소음 가해? &quot;억울해&quot; / JTBC...,2시간 전,@가린마-b1t,서대구역 7 구역 이라고 들었는데 7단지인지 정확히는 잘모르겠지만 부실공사에 제값...,서대구역 구역 이라고 들었는데 단지인지 정확히는 잘모르겠지만 부실공사에 제값보다 고...,"[서대구역, 구역, 들다, 단지, 정확하다, 모르다, 부실, 공사, 값, 평가, 되..."
8,엘베 안 흉기에 40차례…층간 소음 가해? &quot;억울해&quot; / JTBC...,2시간 전,@dongwonkim1223,아파트 층간소음 불만충들. 나무아파트에서 강제로 1달 살게 하기 법을 만듭시다.,아파트 층간소음 불만충들 나무아파트에서 강제로 살게 하기 법을 만듭시다,"[아파트, 층간소음, 불만, 충, 나무, 아파트, 강제, 살, 하다, 법, 만듭시]"
9,엘베 안 흉기에 40차례…층간 소음 가해? &quot;억울해&quot; / JTBC...,2시간 전(수정됨),@김혜정-l8c,정신병자를 이웃으로만난게 불운이였다ㅜㅜ\n조현병같은데 왜 그냥 둔거야,정신병자를 이웃으로만난게 불운이였다 조현병같은데 둔거야,"[정신병, 이웃, 난, 불다, 조현병, 같다, 두다]"
...,...,...,...,...,...,...
45502,&quot;저도 층간소음 피해자입니다&quot; 소음전문 변호사가 소송 말리는 이유,3년 전(수정됨),@Ji-P,@김빠빠-j2k 진짜 저도 딱 이 심정... \n난 그래도 이분에 비하면 다행인...,심정 이분에 비하면 다행인게 새벽 정도면 자서 그런가 조용해지는데 현재 추석이고 코...,"[심정, 이분, 비, 하다, 다행, 새벽, 정도, 자서, 런가, 조용하다, 현재, ..."
45505,&quot;저도 층간소음 피해자입니다&quot; 소음전문 변호사가 소송 말리는 이유,1년 전,@진리-l3w,난 옆집이 존나 시끄럽던대요 코콜이 소리까지 다 들림,옆집이 존나 시끄럽던대요 코콜이 소리까지 들림,"[옆집, 존나, 시끄럽다, 대요, 코콜, 소리, 들리다]"
45508,&quot;저도 층간소음 피해자입니다&quot; 소음전문 변호사가 소송 말리는 이유,2년 전,@worldclass2510Trillion,네 진짜 짐승들입니다 인간도 아닙니다\n저도 겪고 있는데 애미애비 자식새끼들\n다 ...,짐승들입니다 인간도 아닙니다 겪고 애미애비 자식새끼들 똑같애요 죽여버리고 싶습니다 ...,"[짐승, 들이다, 인간, 아니다, 겪다, 애, 미애, 비, 자식새끼, 똑같다, 애,..."
45509,&quot;저도 층간소음 피해자입니다&quot; 소음전문 변호사가 소송 말리는 이유,2년 전,@worldclass2510Trillion,수시로 뭔가로 찍어댑니다\n애비애미도 수시로 오르락내리락 거리고 복층에서 찍어대고 ...,수시로 뭔가로 찍어댑니다 애비애미도 수시로 오르락내리락 거리고 복층에서 찍어대고 애...,"[뭔가, 찍다, 대다, 애비, 애, 미도, 오르락내리락, 거리, 복층, 찍다, 대고..."
45511,&quot;저도 층간소음 피해자입니다&quot; 소음전문 변호사가 소송 말리는 이유,3년 전,@EOh-ew2qf,@사과나무-c8v 애사진 프사로 걸어놓은것만 봐도 요즘 무개념 부모들 중 하나구...,애사진 프사로 걸어놓은것만 봐도 요즘 무개념 부모들 하나구만 아랫층 힘들거 뻔하게 ...,"[애, 사진, 프사, 걸다, 보다, 요즘, 무, 개념, 부모, 하나, 구만, 층, ..."

In [17]:
# 특정 컬럼 제거
# errors='ignore'를 추가하면 해당 컬럼이 데이터프레임에 없더라도 오류 없이 실행됩니다.
df = df.drop(['author', 'title','contents','date'], axis=1, errors='ignore')

# 컬럼이 잘 제거되었는지 확인
print(df.columns)

Index(['contents_clean', 'token'], dtype='object')

In [18]:
df

,contents_clean,token
2,가족들 그엘베 타는거 고역이겠다 어떻게 사냐,"[가족, 엘베, 타다, 고역, 겠다, 어떻다, 사다]"
6,엘베에서 층간소음으로 다툰적이 전세벽에 세탁기를 돌리시더라구요,"[엘베, 층간소음, 다투다, 벽, 세탁기, 돌리다]"
7,서대구역 구역 이라고 들었는데 단지인지 정확히는 잘모르겠지만 부실공사에 제값보다 고...,"[서대구역, 구역, 들다, 단지, 정확하다, 모르다, 부실, 공사, 값, 평가, 되..."
8,아파트 층간소음 불만충들 나무아파트에서 강제로 살게 하기 법을 만듭시다,"[아파트, 층간소음, 불만, 충, 나무, 아파트, 강제, 살, 하다, 법, 만듭시]"
9,정신병자를 이웃으로만난게 불운이였다 조현병같은데 둔거야,"[정신병, 이웃, 난, 불다, 조현병, 같다, 두다]"
...,...,...
45502,심정 이분에 비하면 다행인게 새벽 정도면 자서 그런가 조용해지는데 현재 추석이고 코...,"[심정, 이분, 비, 하다, 다행, 새벽, 정도, 자서, 런가, 조용하다, 현재, ..."
45505,옆집이 존나 시끄럽던대요 코콜이 소리까지 들림,"[옆집, 존나, 시끄럽다, 대요, 코콜, 소리, 들리다]"
45508,짐승들입니다 인간도 아닙니다 겪고 애미애비 자식새끼들 똑같애요 죽여버리고 싶습니다 ...,"[짐승, 들이다, 인간, 아니다, 겪다, 애, 미애, 비, 자식새끼, 똑같다, 애,..."
45509,수시로 뭔가로 찍어댑니다 애비애미도 수시로 오르락내리락 거리고 복층에서 찍어대고 애...,"[뭔가, 찍다, 대다, 애비, 애, 미도, 오르락내리락, 거리, 복층, 찍다, 대고..."
45511,애사진 프사로 걸어놓은것만 봐도 요즘 무개념 부모들 하나구만 아랫층 힘들거 뻔하게 ...,"[애, 사진, 프사, 걸다, 보다, 요즘, 무, 개념, 부모, 하나, 구만, 층, ..."

In [19]:
df.to_csv("유튜브 전처리 후 토크나이징까지.csv", index=False, encoding='utf-8-sig')

print(" 데이터 저장 완료!")

 데이터 저장 완료!